project:
  type: website
  output-dir: docs
  resources:
    - styles.css
    - ToddCao_Resume.pdf

website:
  title: "<img src='image/logo1.png' style='height:40px;'>"
  navbar:
    left:
      - href: 1_index.qmd
        text: Home
      - 2_Publications.qmd
      - 3_Research.qmd
      - 4_Teaching.qmd
      - 5_Achievements.qmd
      - 6_Freelance.qmd
      - 8_Contact.qmd

format:
  html:
    theme: zephyr
    mainfont: arial
    fontsize: 1rem
    linkcolor: "#C8102E"
    css: styles.css
    toc: true


