---
title: "Research records"
---

## Academic work

:::{#tab-fund}

| Paper | Status | Journal ranking |
|---------------|------|---------------|
| **Cao, T. T.**, Prentice, C., Wang, Q., & Nguyen, H. S. (2025). Financial self-discrepancy, consumer well-being, and luxury preferences: The moderating effect of access-based luxury formats. *Psychology & Marketing*. [https://doi.org/10.1002/mar.70057](https://doi.org/10.1002/mar.70057) | Published | Q1 JCR, <br> A-ranked ABDC |
| **Cao, T. T.**, Prentice, C., Wang, Q., & Nguyen, H. S. (2026). Conflicted by faith, drawn to pleasure: How religious self-discrepancy shapes product choices. *International Journal of Consumer Studies* [https://doi.org/10.1111/ijcs.70202](https://doi.org/10.1111/ijcs.70202) | Published | Q1 JCR, <br> A-ranked ABDC |
| **Cao, T. T.**, Prentice, C., Wang, Q., & Nguyen, H. S. (2025). Compensatory consumption: A review and research agenda using the Theory‐Context‐Characteristics‐Methodology framework. *International Journal of Consumer Studies*, *49*(5), e70112.[https://doi.org/10.1111/ijcs.70112](https://doi.org/10.1111/ijcs.70112) | Published | Q1 JCR, <br> A-ranked ABDC |
| **Cao, T. T.** (2025). Self-discrepancy and gambling retention: A conceptual model of motivational and moral pathways. *Strategic Business Research*, 100001.[https://doi.org/10.1016/j.sbr.2025.100001](https://doi.org/10.1016/j.sbr.2025.100001) | Published | Elsevier, <br> peer-reviewed journal |
| **Cao, T. T.**, Nguyen, H. S. (2025). Navigating dual identities: How bicultural consumers leverage luxury consumption to cope with perceived discrimination and enhance well-being. *Journal of Development and Integration*. [https://doi.org/10.61602/jdi.2025.85.12](https://doi.org/10.61602/jdi.2025.85.12) | Published | Elsevier, <br> peer-reviewed journal |
| Ha, N. M., & **Cao, T. T.** (2019). Constructing athlete identification and the effectiveness of athlete endorsement on customer’s purchase intention. *Journal of Distribution Science*, 17(8). [https://doi.org/10.15722/jds.17.8.201908.87](https://doi.org/10.15722/jds.17.8.201908.87) | Published | Peer-reviewed journal |
| Mai, N., **Cao, T. T.**, & Yunen, Z. (2025). How hotels communicate sustainability goal revisions: The role of perceived green-rinsing, influencer type, and sustainability solutions. *Journal of Sustainable Research*. | First Revision | Q1 JCR, <br> A*-ranked ABDC |
| **Cao, T. T.**, Tuan, N. P., & Yunen, Z. (2026). When Generative Artificial Intelligence becomes a counsellor: How employee evaluations shape engagement and organizational attractiveness. *Journal of Enterprise Information Management*. | First Revision | Q1 JCR, <br> A-ranked ABDC |
| **Cao, T. T**, & Tuan, N. P. (2026). Understanding consumer purchase intention toward ZeroClick GenAI-generated recommendations: Evidence from structural equation modeling and machine learning. *Journal of Internet Commerce*. | First Revision | Q1 JCR, <br> B-ranked ABDC |
| Mai, N., **Cao, T. T.**, Yunen, Z. & Tingwen X. (2025). Deepfake versus Virtual Influencers: How Influencer Diversity and Corporate Social Responsibility Shape Consumer Ethicality and Engagement. *Journal of Business Ethics*. | Under Review | Q1 JCR, <br> FT50 |
| **Cao, T. T.**, Mai, N., & Yunen, Z. (2025). Deepfake versus human influencers in hospitality marketing: The roles of emotional exhaustion, autonomy, and identity similarity in shaping booking intention. *Annals of Tourism Research*. | Under Review | Q1 JCR, <br> A*-ranked ABDC |
| Mai, N., **Cao, T. T.**, & Yunen, Z. (2025). The right endorser for the right stay: How human and AI endorsers differ across privacy levels and service modes in accommodation booking intention. *Journal of Travel Research*. | Under Review | Q1 JCR, <br> A*-ranked ABDC |
| Huong, P. N. Q., **Cao, T. T.**, & Thinh, D. H. L. (2026). Revaluing waste: The roles of true- to-ideal authenticity, actual-ought discrepancy, and user-generated content in willing- ness to pay for upcycled food. *The Australian Journal of Agricultural and Resource Economics* | Under Review | Q1 JCR, <br> A-ranked ABDC |

:::

## Conference

:::{#tab-fund}

| Name | Year | Location | Status |
|--------------------------------------------------------|---|------------------------------------|---------------|
| Intelligent Knowledge for Sustainable Organizations (IFKAD) | 2026 | Hungary | Accepted Paper |
| Queensland Marketing Research Group Conference | 2025 | Australia | Attendee |
| Queensland Marketing Research Group Conference | 2024 | Australia | Attendee |
| Integrate Conference | 2022 | West Virginia University | Attendee |
| Living Planet Symposium  | 2022 | European Space Agency | Attendee |
| Third International Conference on Business | 2019 | University of Economics | Presenter |

:::
